#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8 on Wed Jan 22 13:31:59 2014
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
from RootGUI import RootGUI

if __name__ == "__main__":

    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    rf = RootGUI(None, wx.ID_ANY, "")
    app.SetTopWindow(rf)
    rf.Show()
    app.MainLoop()