#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8 on Tue Jan 21 15:42:16 2014
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx

try:
    from RootFrame import RootFrame
except ImportError:
    print 'Importing installed GUI...'
    from shs.gui.RootFrame import RootFrame
    
if __name__ == "__main__":

    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    rf = RootFrame(None, wx.ID_ANY, "")
    app.SetTopWindow(rf)
    rf.Show()
    app.MainLoop()