# -*- coding: utf-8 -*-
# generated by wxGlade HG on Fri Jan 13 14:51:14 2012

import wx

import mbox

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class StepsDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: StepsDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.IsRange = wx.CheckBox(self, -1, "Range")
        self.label_1 = wx.StaticText(self, -1, "Steps")
        self.StartTC = wx.TextCtrl(self, -1, "-1")
        self.label_2 = wx.StaticText(self, -1, "Stop")
        self.StopTC = wx.TextCtrl(self, -1, "")
        self.label_3 = wx.StaticText(self, -1, "Step")
        self.StepTC = wx.TextCtrl(self, -1, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_CHECKBOX, self.IsRangeCheck, self.IsRange)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: StepsDialog.__set_properties
        self.SetTitle("Select steps range")
        self.label_2.Enable(False)
        self.StopTC.Enable(False)
        self.label_3.Enable(False)
        self.StepTC.Enable(False)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: StepsDialog.__do_layout
        StepsSizer = wx.BoxSizer(wx.VERTICAL)
        RangeSizer = wx.GridSizer(3, 2, 2, 2)
        StepsSizer.Add(self.IsRange, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        RangeSizer.Add(self.label_1, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        RangeSizer.Add(self.StartTC, 0, wx.EXPAND, 2)
        RangeSizer.Add(self.label_2, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        RangeSizer.Add(self.StopTC, 0, wx.EXPAND, 0)
        RangeSizer.Add(self.label_3, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        RangeSizer.Add(self.StepTC, 0, wx.EXPAND, 0)
        StepsSizer.Add(RangeSizer, 0, wx.ALL|wx.EXPAND, 5)
        StepsSizer.Add(self.CreateButtonSizer(wx.OK|wx.CANCEL),0,wx.ALL|wx.EXPAND,5)         
        self.SetSizer(StepsSizer)
        StepsSizer.Fit(self)
        self.Layout()
        # end wxGlade
#        StepsSizer.Add(self.CreateButtonSizer(wx.OK|wx.CANCEL))        

    def IsRangeCheck(self, event): # wxGlade: StepsDialog.<event_handler>
        if self.IsRange.GetValue():
            self.label_1.SetLabel('Start')
        else:
            self.label_1.SetLabel('Steps')
        self.label_2.Enable(self.IsRange.GetValue())
        self.StopTC.Enable(self.IsRange.GetValue())
        self.label_3.Enable(self.IsRange.GetValue())
        self.StepTC.Enable(self.IsRange.GetValue())

    def GetRange(self):
        start = self.StartTC.GetValue()
        stop = self.StopTC.GetValue()
        step = self.StepTC.GetValue()
        try:
            if self.IsRange.GetValue():
                r = range(int(start), int(stop), int(step))
            else:
                r = [int(x) for x in start.split()]
        except:
            mbox.WrongInput()
            raise
        return r

# end of class StepsDialog


